name: r2scareer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.5.3
  loader_overlay: ^5.0.0
  intl_phone_number_input: ^0.7.4
  pinput: ^5.0.1
  fluttertoast: ^8.2.12
  provider: ^6.1.4
  http: ^1.3.0
  video_player: ^2.9.5
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  flutter_tts: ^4.2.2
  url_launcher: ^6.3.1
  archive: ^4.0.7
  xml: ^6.5.0
  async: ^2.12.0
  image_picker: ^1.1.2
  pdf: ^3.11.3
  flutter_colorpicker: ^1.1.0
  printing: ^5.14.2
  firebase_storage: ^12.4.5
  screenshot: ^3.0.0
  file_picker: ^10.1.2
  flutter_pdfview: ^1.4.0+1
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  audioplayers: ^6.4.0
  record: ^6.0.0
  camera: ^0.11.1
  flutter_webrtc: ^0.13.1+hotfix.1
  syncfusion_flutter_pdfviewer: ^29.1.39
  open_file: ^3.5.10
  google_sign_in: ^6.3.0
  flutter_markdown: ^0.7.7

dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.jpg
  android: true
  ios: true
  web: false
  android_gravity: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
