// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsA8xN7XnUL7-9rdTERoHFMjpMOpUjMLg',
    appId: '1:548104130703:web:3d91c7819d2bfb40fc20fa',
    messagingSenderId: '548104130703',
    projectId: 'r2scareer-9ef27',
    authDomain: 'r2scareer-9ef27.firebaseapp.com',
    storageBucket: 'r2scareer-9ef27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN19Wb18jW3hQI2ewuINVKt3BGJPrZfG8',
    appId: '1:548104130703:android:6e5930a62c373439fc20fa',
    messagingSenderId: '548104130703',
    projectId: 'r2scareer-9ef27',
    storageBucket: 'r2scareer-9ef27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN87OnjRbS8VbRetABORFMqA0F6aMKf4Y',
    appId: '1:548104130703:ios:aca4f423ab01a8cbfc20fa',
    messagingSenderId: '548104130703',
    projectId: 'r2scareer-9ef27',
    storageBucket: 'r2scareer-9ef27.firebasestorage.app',
    iosClientId: '548104130703-4iaimmgsidf74sp4ltgmegvk5tuoi405.apps.googleusercontent.com',
    iosBundleId: 'com.example.r2scareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN87OnjRbS8VbRetABORFMqA0F6aMKf4Y',
    appId: '1:548104130703:ios:aca4f423ab01a8cbfc20fa',
    messagingSenderId: '548104130703',
    projectId: 'r2scareer-9ef27',
    storageBucket: 'r2scareer-9ef27.firebasestorage.app',
    iosClientId: '548104130703-4iaimmgsidf74sp4ltgmegvk5tuoi405.apps.googleusercontent.com',
    iosBundleId: 'com.example.r2scareer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsA8xN7XnUL7-9rdTERoHFMjpMOpUjMLg',
    appId: '1:548104130703:web:5dc01c016dbb8fe5fc20fa',
    messagingSenderId: '548104130703',
    projectId: 'r2scareer-9ef27',
    authDomain: 'r2scareer-9ef27.firebaseapp.com',
    storageBucket: 'r2scareer-9ef27.firebasestorage.app',
  );
}
